export enum DepartmentKeysEnum {
  INTERPRETATION = "INTERPRETATION",
  PROGRAMME = "PROGRAMME",
  MEDIA = "MEDIA",
  TREASURY = "TREASURY",
  TECHNICAL = "TECHNICAL",
  DRAMA = "DRAMA",
  IT = "IT",
  EVANGELISM = "EVANGELISM",
  SANITATION = "SANITATION",
  SECRETARIAT = "SECRETARIAT",
}
