import { BandKeysEnum } from "@/enums/bands";

// Band Configuration
export const BANDS_CONFIG = {
  [BandKeysEnum.CHOIR]: {
    id: BandKeysEnum.CHOIR,
    name: "Choir",
    icon1: "music.note",
    icon2: "IoMusicalNoteOutline",
    gradient: ["#8B5CF6", "#A855F7"],
    meetingDay: "",
    meetingTime: "",
    description: "Leading worship through songs and hymns.",
  },
  [BandKeysEnum.LOVE_DIVINE]: {
    id: BandKeysEnum.LOVE_DIVINE,
    name: "Love Divine",
    icon1: "heart.fill",
    icon2: "IoHeartOutline",
    gradient: ["#EC4899", "#BE185D"],
    meetingDay: "",
    meetingTime: "",
    description: "Spreading God's love through service and fellowship.",
  },
  [BandKeysEnum.DANIEL]: {
    id: BandKeysEnum.DANIEL,
    name: "Daniel",
    icon1: "shield.fill",
    icon2: "IoShieldOutline",
    gradient: ["#3B82F6", "#1E40AF"],
    meetingDay: "",
    meetingTime: "",
    description: "Standing firm in faith and righteousness.",
  },
  [BandKeysEnum.DEBORAH]: {
    id: BandKeysEnum.DEBORAH,
    name: "Deborah",
    icon1: "sparkles",
    icon2: "IoSparklesOutline",
    gradient: ["#10B981", "#047857"],
    meetingDay: "",
    meetingTime: "",
    description: "Women of strength and wisdom in leadership.",
  },
  [BandKeysEnum.QUEEN_ESTHER]: {
    id: BandKeysEnum.QUEEN_ESTHER,
    name: "Queen Esther",
    icon1: "crown.fill",
    icon2: "IoWomanOutline",
    gradient: ["#F59E0B", "#D97706"],
    meetingDay: "",
    meetingTime: "",
    description: "For such a time as this — serving with purpose.",
  },
  [BandKeysEnum.GOOD_WOMEN]: {
    id: BandKeysEnum.GOOD_WOMEN,
    name: "Good Women",
    icon1: "person.2.fill",
    icon2: "IoWomanOutline",
    gradient: ["#EF4444", "#DC2626"],
    meetingDay: "",
    meetingTime: "",
    description: "Virtuous women building the kingdom.",
  },
  [BandKeysEnum.WARDEN]: {
    id: BandKeysEnum.WARDEN,
    name: "Warden",
    icon1: "shield.lefthalf.filled",
    icon2: "IoShieldHalfOutline",
    gradient: ["#6B7280", "#374151"],
    meetingDay: "",
    meetingTime: "",
    description: "Guardians of the church and its values.",
  },
  [BandKeysEnum.JOHN_BELOVED]: {
    id: BandKeysEnum.JOHN_BELOVED,
    name: "John Beloved",
    icon1: "person.fill.checkmark",
    icon2: "IoPersonAddOutline",
    gradient: ["#06B6D4", "#0891B2"],
    meetingDay: "",
    meetingTime: "",
    description: "Beloved disciples walking in love and truth.",
  },
  [BandKeysEnum.FAITH]: {
    id: BandKeysEnum.FAITH,
    name: "Faith",
    icon1: "hands.sparkles.fill",
    icon2: "IoStarOutline",
    gradient: ["#8B5CF6", "#7C3AED"],
    meetingDay: "",
    meetingTime: "",
    description: "Walking by faith, not by sight.",
  },
  [BandKeysEnum.HOLY_MARY]: {
    id: BandKeysEnum.HOLY_MARY,
    name: "Holy Mary",
    icon1: "star.circle.fill",
    icon2: "IoStarOutline",
    gradient: ["#3B82F6", "#1D4ED8"],
    meetingDay: "",
    meetingTime: "",
    description: "Blessed among women, serving with humility.",
  },
  [BandKeysEnum.UNASSIGNED]: {
    id: BandKeysEnum.UNASSIGNED,
    name: "Unassigned",
    icon1: "person.question",
    icon2: "IoHelpCircleOutline",
    gradient: ["#9CA3AF", "#6B7280"],
    meetingDay: "",
    meetingTime: "",
    description: "Members not assigned to any band",
  },
};
